// SPDX-License-Identifier: MIT
pragma solidity >=0.4.22;

/**
 * @title JoyueLib
 * @dev Solidity SDK for JOYUE V1.4 §6: "assert wrapper" + "if-else conditionals"
 *      that generate Guards/Deltas while executing business logic on an Agent (cache-based) contract.
 *
 * IMPORTANT:
 * - Agent reads state ONLY from cache (P2P cache in the real system).
 * - Agent outputs an Intent (Guards + Deltas + RawRequest) to be sent to Master for authoritative verify/commit.
 *
 * TODO(P2P Cache):
 * - Replace `IJoyueCache` mock interface integration with node-level P2P cache plumbing.
 * - Each node will maintain cache entries for (contractAddr,key) -> (value, version).
 * - Solidity should only call the cache contract (or a precompile) exposed by the node.
 */
// P2P cache接口（读）
interface IJoyueCache {
    function get(address contractAddr, bytes32 key) external view returns (bytes memory value, uint64 version, bool ok);
}

// 可选写接口（用于 Agent 侧 mock/可写缓存快进）
interface IJoyueCacheWriter {
    function setUint(address contractAddr, bytes32 key, uint256 value, uint64 version) external;
}

library JoyueLib {
    // ============================================================
    //                      Enums / Consts
    // ============================================================

    // Guard ops (V1.4 §5.1)
    uint8 public constant OP_EQ = 0x01;
    uint8 public constant OP_NEQ = 0x02;
    uint8 public constant OP_GT = 0x03;
    uint8 public constant OP_GTE = 0x04;
    uint8 public constant OP_LT = 0x05;
    uint8 public constant OP_LTE = 0x06;
    uint8 public constant OP_EXPR = 0xFF; // RPN expression guard

    // Delta ops (V1.4 §5.1)
    uint8 public constant D_ADD = 0x01;
    uint8 public constant D_SUB = 0x02;
    uint8 public constant D_SET = 0x10;
    uint8 public constant D_BIT_OR = 0x20;
    uint8 public constant D_BIT_CLEAR = 0x21;
    uint8 public constant D_BIT_XOR = 0x22;
    uint8 public constant D_LOG = 0xFF;

    // Guard strategy (V1.4 §6.1.2)
    uint8 public constant STRATEGY_STRICT = 0x00;
    uint8 public constant STRATEGY_RELAXED = 0x01;

    // Expr token kinds (for OP_EXPR payload)
    uint8 internal constant TOK_VAR = 0x01;   // (contractAddr,key,version)
    uint8 internal constant TOK_ARG = 0x02;   // (argIndex)
    uint8 internal constant TOK_CONST = 0x03; // (uint256)
    uint8 internal constant TOK_OP = 0x04;    // (opcode)

    // Expr math ops (minimal set for demo)
    uint8 internal constant EXPR_ADD = 0x01;
    uint8 internal constant EXPR_SUB = 0x02;
    uint8 internal constant EXPR_MUL = 0x03;
    uint8 internal constant EXPR_DIV = 0x04;

    // ============================================================
    //                      Data Structures
    // ============================================================

    struct Guard {
        address contractAddr; // target contract (Master) whose state is guarded
        uint32 shardId;       // target shardId of the contract
        bytes32 key;          // state key
        uint64 readVersion;   // cache version read by agent
        uint8 strategy;       // STRICT / RELAXED
        uint8 op;             // OP_*
        bytes val;            // abi.encode(uint256) for atomic, or abi-encoded RPN payload for OP_EXPR
    }

    struct Delta {
        address contractAddr; // target contract (Master) whose state will be modified
        uint32 shardId;       // target shardId of the contract
        bytes32 key;
        uint8 op;             // D_*
        bytes val;            // abi.encode(uint256) / bytes
    }

    /**
     * @dev RawRequest is the "retry base": Master uses (targetAddr, selector, args) to replay logic tree.
     */
    struct RawRequest {
        address targetAddr; // Master contract entry
        bytes4 selector;
        bytes args;         // original function args (abi.encode(...))
    }

    /// @dev 用于 recomputeIntent 的状态覆盖：callback 返回的权威最新状态，优先于缓存
    struct StateOverride {
        address contractAddr;
        uint32 shardId;
        bytes32 key;
        uint256 value;
        uint64 version;
    }

    struct Context {
        Guard[] guards;
        Delta[] deltas;
        RawRequest req;
        address cacheAddr;  // cache contract / precompile address exposed by node
        uint32 shardId;     // current shardId for this agent
        bytes32 txId;       // unique per-transaction identifier (generated by _nextTxId)
    }

    /**
     * @dev JVar wraps a state variable read from cache.
     */
    struct JVar {
        address contractAddr;
        uint32 shardId;
        bytes32 key;
        bytes value;
        uint64 version;
        bool loaded;
    }

    /**
     * @dev RPN expression builder. It also evaluates using cached values to decide branch direction,
     * while emitting an OP_EXPR Guard with correct comparator (positive or inverse).
     */
    struct ExprBuilder {
        bytes[] tokens;      // serialized tokens
        uint256[] evalStack; // runtime eval stack (cached values)
    }

    // ============================================================
    //                      Events
    // ============================================================

    event IntentEmitted(
        address indexed targetAddr,
        bytes4 indexed selector,
        bytes args,
        Guard[] guards,
        Delta[] deltas
    );

    // ============================================================
    //                      TX Counter (固定存储槽，JoyueLib 管理)
    // ============================================================

    // keccak256("joyue.txCounter.v1") — 确定性槽位，避免与业务存储碰撞
    bytes32 private constant TX_COUNTER_SLOT = 0x9a81b3eced7b5b8d62e62af49a60e80f5f5a2d2cfdd978e1a3a0bc8a6f5e0391;

    /**
     * @dev 生成本合约内单调递增的交易标识符。
     *      使用固定存储槽，不会与业务变量冲突。
     *      因涉及 sstore，调用方不能是 view 函数。
     */
    function _nextTxId() internal returns (bytes32) {
        uint256 counter;
        bytes32 slot = TX_COUNTER_SLOT;
        assembly {
            counter := sload(slot)
            counter := add(counter, 1)
            sstore(slot, counter)
        }
        return keccak256(abi.encodePacked(address(this), counter, block.number));
    }

    // ============================================================
    //                      Context
    // ============================================================

    /**
     * @dev 创建只读上下文（不生成 txId），用于 view 函数 / 调试。
     */
    function newContext(address cacheAddr, address targetAddr, bytes4 selector, bytes memory args)
        internal
        view
        returns (Context memory ctx)
    {
        ctx.cacheAddr = cacheAddr;
        ctx.req = RawRequest({targetAddr: targetAddr, selector: selector, args: args});
        ctx.shardId = _getCurrentShardID();
        // txId = bytes32(0) 表示无 freeze 语义
    }

    /**
     * @dev 创建交易上下文，自动生成全局唯一 txId，用于真实交易（非 view）。
     *      D_SUB 操作会使用 txId 在本地冻结表中预占资源。
     */
    function newTransactionContext(address cacheAddr, address targetAddr, bytes4 selector, bytes memory args)
        internal
        returns (Context memory ctx)
    {
        ctx.cacheAddr = cacheAddr;
        ctx.req = RawRequest({targetAddr: targetAddr, selector: selector, args: args});
        ctx.shardId = _getCurrentShardID();
        ctx.txId = _nextTxId();
    }

    function emitIntent(Context memory ctx) internal {
        emit IntentEmitted(ctx.req.targetAddr, ctx.req.selector, ctx.req.args, ctx.guards, ctx.deltas);
    }

    // ============================================================
    //      预编译合约调用（通过 CrossShardRequest 事件）
    // ============================================================

    // 预编译合约地址常量
    address public constant PRECOMPILE_RPC_ORACLE = address(0x6D);  // RPC Oracle 预编译（发出 CrossShardRequest 事件）
    address public constant PRECOMPILE_EXECUTOR = address(0x74);    // Executor 预编译（统一收口跨分片调用）
    address public constant PRECOMPILE_CURRENT_SHARD = address(0x6C); // 当前分片 ID 预编译
    address public constant PRECOMPILE_CACHE_READ = address(0x64);   // 缓存读取预编译（0x64 = 100）
    address public constant PRECOMPILE_CACHE_WRITE = address(0x65);  // 缓存写入预编译（0x65 = 101）

    /**
     * @dev 通过预编译合约发出跨分片 Intent 请求
     * @param ctx 上下文（包含 guards, deltas, req）
     * @param targetShardID 目标分片 ID
     * @param masterAddr Master 合约地址
     * @param executorAddr Executor 预编译地址（默认 0x74）
     * @param callbackAddr 回调地址（可选，如果需要回调）
     * @param callbackSelector 回调函数选择器（可选）
     * @param requestId 请求 ID（用于追踪，如果为 0 则自动生成）
     * @return success 是否成功发出事件
     */
    function emitIntentViaPrecompile(
        Context memory ctx,
        uint32 targetShardID,
        address masterAddr,
        address executorAddr,
        address callbackAddr,
        bytes4 callbackSelector,
        uint256 requestId
    ) internal returns (bool success) {
        // 构建 payload
        bytes memory payload = _buildIntentPayload(ctx);
        
        // 构建 executor calldata
        bytes memory executorCalldata = _buildExecutorCalldata(
            payload,
            masterAddr,
            callbackAddr,
            callbackSelector,
            requestId == 0 ? _generateRequestId(ctx) : requestId
        );
        
        // 调用预编译合约发出事件
        success = _emitCrossShardRequestEvent(targetShardID, executorAddr, executorCalldata);
    }

    /**
     * @dev 构建 Intent payload（内部函数，减少堆栈深度）
     *      txId 直接取自 ctx.txId（由 newTransactionContext 生成）。
     */
    function _buildIntentPayload(Context memory ctx) private view returns (bytes memory payload) {
        // 使用 ctx.txId（由 newTransactionContext 生成，单调唯一）
        // 若 ctx.txId == 0（view 上下文），则回退到基于内容的哈希（仅用于调试路径）
        bytes32 txId = ctx.txId != bytes32(0)
            ? ctx.txId
            : keccak256(abi.encodePacked(block.timestamp, msg.sender, ctx.req.args));

        uint32 agentShardId = ctx.shardId;
        address agentContract = address(this);
        uint64 agentBlockNumber = uint64(block.number);
        uint64 nonce = uint64(block.number);

        payload = abi.encode(
            txId,
            agentShardId,
            agentContract,
            agentBlockNumber,
            nonce,
            ctx.req,
            ctx.guards,
            ctx.deltas,
            msg.sender  // 用于 retry 时 recomputeIntent 读取余额/积分
        );
    }

    /**
     * @dev 构建 Executor calldata（内部函数，减少堆栈深度）
     */
    function _buildExecutorCalldata(
        bytes memory payload,
        address masterAddr,
        address callbackAddr,
        bytes4 callbackSelector,
        uint256 requestId
    ) private view returns (bytes memory executorCalldata) {
        // 构建 Master.processIntent(bytes) 的 calldata
        bytes memory processIntentCalldata = abi.encodeWithSignature(
            "processIntent(bytes)",
            payload
        );

        // 构建 Executor.executeAndCallback 的 calldata
        executorCalldata = abi.encodeWithSelector(
            0x2b5d76a4,  // executeAndCallback selector
            _getCurrentShardID(),  // sourceShardID
            callbackAddr,
            callbackSelector,
            requestId,
            masterAddr,
            uint256(0),  // value
            processIntentCalldata
        );
    }

    /**
     * @dev 发出 CrossShardRequest 事件（内部函数，减少堆栈深度）
     */
    function _emitCrossShardRequestEvent(
        uint32 targetShardID,
        address executorAddr,
        bytes memory executorCalldata
    ) private returns (bool success) {
        // 构建预编译合约输入
        // 格式：4 bytes (shardID) + 20 bytes (to) + 32 bytes (value) + 4 bytes (calldataLen) + calldata
        uint256 calldataLen = executorCalldata.length;
        uint256 totalLen = 60 + calldataLen;
        
        address precompileAddr = PRECOMPILE_RPC_ORACLE;
        
        // 使用 assembly 高效构建输入并调用预编译合约
        assembly {
            // 分配内存：length (32 bytes) + data
            let inputPtr := mload(0x40)  // 获取空闲内存指针
            mstore(0x40, add(inputPtr, add(0x20, totalLen)))  // 更新空闲内存指针
            
            // 存储 length
            mstore(inputPtr, totalLen)
            let dataPtr := add(inputPtr, 0x20)
            
            // 1. shardID (4 bytes, big-endian) at offset 0
            mstore8(dataPtr, shr(24, targetShardID))
            mstore8(add(dataPtr, 1), shr(16, targetShardID))
            mstore8(add(dataPtr, 2), shr(8, targetShardID))
            mstore8(add(dataPtr, 3), targetShardID)
            
            // 2. executorAddr (20 bytes) at offset 4
            let addrPtr := add(dataPtr, 4)
            mstore(addrPtr, shl(96, executorAddr))  // 左移 96 bits (12 bytes) 将地址放在最后 20 bytes
            
            // 3. value (32 bytes, 0) at offset 24 - already zero by default (mstore 会清零)
            // 跳过，因为内存已经清零
            
            // 4. calldataLen (4 bytes, big-endian) at offset 56
            let lenPtr := add(dataPtr, 56)
            mstore8(lenPtr, shr(24, calldataLen))
            mstore8(add(lenPtr, 1), shr(16, calldataLen))
            mstore8(add(lenPtr, 2), shr(8, calldataLen))
            mstore8(add(lenPtr, 3), calldataLen)
            
            // 5. calldata (bytes) at offset 60 - 使用高效的内存复制（批量复制 32 bytes）
            if gt(calldataLen, 0) {
                let calldataPtr := add(dataPtr, 60)
                let calldataSrcPtr := add(executorCalldata, 0x20)  // 跳过 length
                
                // 批量复制：每次复制 32 bytes
                let i := 0
                for { } lt(i, calldataLen) { i := add(i, 32) } {
                    // 读取源数据（32 bytes）
                    let srcData := mload(add(calldataSrcPtr, i))
                    // 写入目标位置
                    mstore(add(calldataPtr, i), srcData)
                }
            }
            
            // 调用预编译合约（会发出 CrossShardRequest 事件）
            success := call(
                gas(),
                precompileAddr,
                0,
                dataPtr,
                totalLen,
                0,
                0
            )
        }
    }

    /**
     * @dev 简化版本：通过预编译合约发出跨分片 Intent 请求（无回调）
     */
    function emitIntentViaPrecompile(
        Context memory ctx,
        uint32 targetShardID,
        address masterAddr
    ) internal returns (bool success) {
        return emitIntentViaPrecompile(
            ctx,
            targetShardID,
            masterAddr,
            PRECOMPILE_EXECUTOR,
            address(0),  // 无回调
            bytes4(0),
            uint256(0)   // 自动生成 requestId
        );
    }

    /**
     * @dev 获取当前分片 ID（通过预编译合约
     * 0x6C）
     */
    function _getCurrentShardID() private view returns (uint32) {
        // 调用预编译合约 0x6C 获取当前分片 ID
        // 返回格式：32 bytes，最后 4 字节是 shardID（大端序）
        (bool success, bytes memory result) = PRECOMPILE_CURRENT_SHARD.staticcall(new bytes(0));
        if (success && result.length >= 32) {
            // 提取最后 4 字节（uint32，大端序）
            // Go 预编译将 shardID 放在 result[28:32]，即 32 字节中的低 32 位
            uint32 shardID;
            assembly {
                // result 是 bytes memory：前 32 字节是 length，数据从 result+0x20 开始
                // mload(result+0x20) 得到完整 32 字节，低 32 位即 data[28:32]
                shardID := and(mload(add(result, 0x20)), 0xffffffff)
            }
            return shardID;
        }
        return 0; // 默认返回 0
    }

    /**
     * @dev 生成请求 ID（基于 Context 内容）
     */
    function _generateRequestId(Context memory ctx) private view returns (uint256) {
        // 使用 block.timestamp, msg.sender, req.args 生成唯一 ID
        return uint256(keccak256(abi.encodePacked(
            block.timestamp,
            msg.sender,
            ctx.req.args,
            ctx.guards.length,
            ctx.deltas.length
        )));
    }

    // ============================================================
    //                      Cache Load
    // ============================================================

    function loadFromCacheByKey(Context memory /* ctx */, address contractAddr, uint32 shardId, bytes32 key)
        internal
        view
        returns (JVar memory v)
    {
        v.contractAddr = contractAddr;
        v.shardId = shardId;
        v.key = key;

        // 直接调用预编译合约读取缓存（不需要通过 JoyueCache 合约）
        // 输入格式：contractAddr (20 bytes) + key (32 bytes)
        bytes memory input = abi.encodePacked(contractAddr, shardId, key);
        
        (bool success, bytes memory result) = PRECOMPILE_CACHE_READ.staticcall(input);
        
        if (success && result.length >= 128) {
            // 解析 precompile 返回结果：abi.encode(bytes value, uint64 version, bool ok)
            // result[0:32] = offset for bytes (应该是 96)
            // result[32:64] = length of bytes
            // result[64:96] = version (uint64, padded to 32 bytes)
            // result[96:128] = ok (bool, padded to 32 bytes)
            // result[128:] = bytes data
            
            // 提取 offset
            uint256 offset;
            assembly {
                offset := mload(add(result, 0x20))
            }
            
            if (offset == 96) {
                // 提取 valueLen
                uint256 valueLen;
                assembly {
                    valueLen := mload(add(result, 0x40))
                }
                
                // 提取 version (64-96 字节，uint64 右对齐在 32 字节中)
                // version 是左填充的，值在最后 8 字节
                uint64 version = uint64(uint256(abi.decode(_slice(result, 64, 96), (uint256))));
                
                // 提取 ok (96-128 字节，bool 右对齐在 32 字节中)
                // ok 是左填充的，值在最后 1 字节
                bool ok = abi.decode(_slice(result, 96, 128), (bool));
                
                if (ok && valueLen > 0 && result.length >= 128 + valueLen) {
                    // 提取 bytes 值
                    bytes memory value = new bytes(valueLen);
                    for (uint256 i = 0; i < valueLen; i++) {
                        value[i] = result[128 + i];
                    }
                    v.value = value;
                    v.version = version;
                } else {
                    // 缓存未命中
                    v.value = bytes("");
                    v.version = 0;
                }
            } else {
                // 格式不正确
                v.value = bytes("");
                v.version = 0;
            }
        } else {
            // Precompile 调用失败，返回空值
            v.value = bytes("");
            v.version = 0;
        }
        
        v.loaded = true;
        return v;
    }

    /// @dev 带 StateOverride 的缓存读取：优先使用 override，否则回退到 loadFromCacheByKey
    function loadFromCacheByKeyWithOverrides(
        Context memory ctx,
        address contractAddr,
        uint32 shardId,
        bytes32 key,
        StateOverride[] memory overrides
    ) internal view returns (JVar memory v) {
        for (uint256 i = 0; i < overrides.length; i++) {
            if (
                overrides[i].contractAddr == contractAddr &&
                overrides[i].shardId == shardId &&
                overrides[i].key == key
            ) {
                v.contractAddr = contractAddr;
                v.shardId = shardId;
                v.key = key;
                v.value = abi.encode(overrides[i].value);
                v.version = overrides[i].version;
                v.loaded = true;
                return v;
            }
        }
        return loadFromCacheByKey(ctx, contractAddr, shardId, key);
    }

    /**
     * @dev 从 bytes 中提取切片（内部辅助函数）
     */
    function _slice(bytes memory data, uint256 start, uint256 end) private pure returns (bytes memory) {
        require(end > start && end <= data.length, "JOYUE: invalid slice range");
        bytes memory result = new bytes(end - start);
        for (uint256 i = 0; i < result.length; i++) {
            result[i] = data[start + i];
        }
        return result;
    }

    // ============================================================
    //                      Key Helpers
    // ============================================================

    function keyOf(string memory s) internal pure returns (bytes32) {
        return keccak256(abi.encodePacked(s));
    }

    function keyOf2(string memory prefix, bytes32 x) internal pure returns (bytes32) {
        return keccak256(abi.encodePacked(prefix, x));
    }

    function keyOfAddr(string memory prefix, address a) internal pure returns (bytes32) {
        return keccak256(abi.encodePacked(prefix, a));
    }

    // ============================================================
    //                      Value Helpers
    // ============================================================

    function toUint(bytes memory b) internal pure returns (uint256) {
        if (b.length < 32) return 0;
        // 直接读取前 32 bytes 作为 uint256，不使用 abi.decode（因为 b 已经是原始 bytes，不是 ABI 编码格式）
        // 注意：bytes memory 在内存中的布局是：length (32 bytes) + data
        // b 是指针，mload(b) = length，mload(add(b, 0x20)) = 第一个 32 bytes 的数据
        // 但是，如果 b.length = 32，那么第一个 32 bytes 就是实际的数据
        // 使用 abi.decode 来确保正确解析（虽然 b 不是 ABI 编码，但我们可以手动构造）
        // 或者直接使用 assembly 读取数据部分
        uint256 result;
        assembly {
            // b 是指针，指向 length
            // add(b, 0x20) 指向数据部分
            // 读取第一个 32 bytes 的数据
            let dataPtr := add(b, 0x20)
            result := mload(dataPtr)
        }
        return result;
    }

    function _pushGuard(Context memory ctx, Guard memory g) private pure {
        Guard[] memory oldG = ctx.guards;
        Guard[] memory newG = new Guard[](oldG.length + 1);
        for (uint256 i = 0; i < oldG.length; i++) {
            newG[i] = oldG[i];
        }
        newG[oldG.length] = g;
        ctx.guards = newG;
    }

    function _addGuard(
        Context memory ctx,
        JVar memory v,
        uint8 op,
        uint256 threshold,
        uint8 strategy
    ) private pure {
        _pushGuard(
            ctx,
            Guard({
                contractAddr: v.contractAddr,
                shardId: v.shardId,
                key: v.key,
                readVersion: v.version,
                strategy: strategy,
                op: op,
                val: abi.encode(threshold)
            })
        );
    }

    function _inverseAtomic(uint8 op) private pure returns (uint8) {
        if (op == OP_GT) return OP_LTE;
        if (op == OP_GTE) return OP_LT;
        if (op == OP_LT) return OP_GTE;
        if (op == OP_LTE) return OP_GT;
        if (op == OP_EQ) return OP_NEQ;
        if (op == OP_NEQ) return OP_EQ;
        return op;
    }

    // ============================================================
    //                      Conditionals (if-else)
    // ============================================================

    function checkGte(JVar memory v, Context memory ctx, uint256 threshold) internal pure returns (bool) {
        uint256 cur = toUint(v.value);
        if (cur >= threshold) {
            _addGuard(ctx, v, OP_GTE, threshold, STRATEGY_RELAXED);
            return true;
        } else {
            _addGuard(ctx, v, OP_LT, threshold, STRATEGY_RELAXED);
            return false;
        }
    }

    function checkGt(JVar memory v, Context memory ctx, uint256 threshold) internal pure returns (bool) {
        uint256 cur = toUint(v.value);
        if (cur > threshold) {
            _addGuard(ctx, v, OP_GT, threshold, STRATEGY_RELAXED);
            return true;
        } else {
            _addGuard(ctx, v, OP_LTE, threshold, STRATEGY_RELAXED);
            return false;
        }
    }

    function checkEq(JVar memory v, Context memory ctx, uint256 target) internal pure returns (bool) {
        uint256 cur = toUint(v.value);
        if (cur == target) {
            _addGuard(ctx, v, OP_EQ, target, STRATEGY_STRICT);
            return true;
        } else {
            _addGuard(ctx, v, OP_NEQ, target, STRATEGY_STRICT);
            return false;
        }
    }

    // Optional "must pass" wrappers (assert style)
    function assertGte(JVar memory v, Context memory ctx, uint256 threshold) internal pure {
        require(checkGte(v, ctx, threshold), "JOYUE: assertGte failed");
    }

    // ============================================================
    //                      Deltas
    // ============================================================

    function _pushDelta(Context memory ctx, Delta memory d) private pure {
        Delta[] memory oldD = ctx.deltas;
        Delta[] memory newD = new Delta[](oldD.length + 1);
        for (uint256 i = 0; i < oldD.length; i++) {
            newD[i] = oldD[i];
        }
        newD[oldD.length] = d;
        ctx.deltas = newD;
    }

    function _addDelta(Context memory ctx, JVar memory v, uint8 op, bytes memory val) private {
        _pushDelta(ctx, Delta({contractAddr: v.contractAddr, shardId: v.shardId, key: v.key, op: op, val: val}));
        _applyCacheWrite(ctx, v, op, val);
    }

    function add(JVar memory v, Context memory ctx, uint256 amount) internal {
        _addDelta(ctx, v, D_ADD, abi.encode(amount));
    }

    function sub(JVar memory v, Context memory ctx, uint256 amount) internal {
        _addDelta(ctx, v, D_SUB, abi.encode(amount));
    }

    function set(JVar memory v, Context memory ctx, uint256 value) internal {
        _addDelta(ctx, v, D_SET, abi.encode(value));
    }

    // ============================================================
    //                      ExprBuilder (RPN)
    // ============================================================

    function expr(Context memory) internal pure returns (ExprBuilder memory b) {
        return b;
    }

    function _pushToken(ExprBuilder memory b, bytes memory tok) private pure returns (ExprBuilder memory) {
        bytes[] memory oldT = b.tokens;
        bytes[] memory newT = new bytes[](oldT.length + 1);
        for (uint256 i = 0; i < oldT.length; i++) newT[i] = oldT[i];
        newT[oldT.length] = tok;
        b.tokens = newT;
        return b;
    }

    function _pushEval(ExprBuilder memory b, uint256 v) private pure returns (ExprBuilder memory) {
        uint256[] memory oldS = b.evalStack;
        uint256[] memory newS = new uint256[](oldS.length + 1);
        for (uint256 i = 0; i < oldS.length; i++) newS[i] = oldS[i];
        newS[oldS.length] = v;
        b.evalStack = newS;
        return b;
    }

    function pushVar(ExprBuilder memory b, JVar memory v) internal pure returns (ExprBuilder memory) {
        // token: [TOK_VAR | addr(20) | key(32) | ver(8)]
        bytes memory t = abi.encodePacked(TOK_VAR, v.contractAddr, v.key, v.version);
        b = _pushToken(b, t);
        b = _pushEval(b, toUint(v.value));
        return b;
    }

    function pushArg(ExprBuilder memory b, uint8 argIndex, uint256 argValue) internal pure returns (ExprBuilder memory) {
        // NOTE: Solidity can't access raw args automatically; caller supplies argValue for evaluation.
        // TODO: standardize arg plumbing for automatic decoding by codegen/macro layer.
        bytes memory t = abi.encodePacked(TOK_ARG, argIndex);
        b = _pushToken(b, t);
        b = _pushEval(b, argValue);
        return b;
    }

    function pushConst(ExprBuilder memory b, uint256 c) internal pure returns (ExprBuilder memory) {
        bytes memory t = abi.encodePacked(TOK_CONST, c);
        b = _pushToken(b, t);
        b = _pushEval(b, c);
        return b;
    }

    function _binOp(ExprBuilder memory b, uint8 op) private pure returns (ExprBuilder memory) {
        require(b.evalStack.length >= 2, "JOYUE: expr stack underflow");
        uint256 len = b.evalStack.length;
        uint256 r = b.evalStack[len - 1];
        uint256 l = b.evalStack[len - 2];

        uint256 out;
        if (op == EXPR_ADD) out = l + r;
        else if (op == EXPR_SUB) out = l - r;
        else if (op == EXPR_MUL) out = l * r;
        else if (op == EXPR_DIV) out = (r == 0) ? 0 : (l / r);
        else revert("JOYUE: bad expr op");

        // stack: pop2 push1 => new length = len - 1
        uint256[] memory newS = new uint256[](len - 1);
        for (uint256 i = 0; i < len - 2; i++) newS[i] = b.evalStack[i];
        newS[len - 2] = out;
        b.evalStack = newS;

        b = _pushToken(b, abi.encodePacked(TOK_OP, op));
        return b;
    }

    function opAdd(ExprBuilder memory b) internal pure returns (ExprBuilder memory) {
        return _binOp(b, EXPR_ADD);
    }

    function opMul(ExprBuilder memory b) internal pure returns (ExprBuilder memory) {
        return _binOp(b, EXPR_MUL);
    }

    function checkExprGt(ExprBuilder memory b, Context memory ctx, uint256 threshold) internal pure returns (bool) {
        require(b.evalStack.length == 1, "JOYUE: expr not reduced");
        bool ok = b.evalStack[0] > threshold;

        // OP_EXPR payload: abi.encode(tokens, cmpOp, threshold)
        uint8 cmp = ok ? OP_GT : OP_LTE;
        _pushGuard(
            ctx,
            Guard({
                contractAddr: ctx.req.targetAddr, // logical owner; execution engine will parse tokens for real routing
                shardId: ctx.shardId,
                key: bytes32(0),                  // unused for expr; routing inside tokens
                readVersion: 0,
                strategy: STRATEGY_RELAXED,
                op: OP_EXPR,
                val: abi.encode(b.tokens, cmp, threshold)
            })
        );
        return ok;
    }

    // ============================================================
    //                      Cache write / Freeze
    // ============================================================

    /**
     * @dev 应用缓存写入或冻结。
     *
     * - D_SUB（消耗资源）：
     *     若 ctx.txId != 0，调用预编译 0x65 的 Freeze 语义，
     *     在本地冻结表中预占 amount。若可用量不足则 revert。
     *     成功后更新 v.value（乐观值）。
     *
     * - D_ADD / D_SET / D_BIT_* （非消耗）：
     *     维持原有快进写缓存逻辑（调用 0x65 的旧语义）。
     *
     * 预编译 0x65 输入格式：
     *   Freeze (D_SUB)   : abi.encode(address, uint32, bytes32, bytes32 txId, uint256 amount)  → 返回 bytes32(1) 成功
     *   Write  (非D_SUB) : abi.encode(address, uint32, bytes32, uint256 value, uint64 version) → 无返回值
     */
    function _applyCacheWrite(Context memory ctx, JVar memory v, uint8 op, bytes memory val) private {
        uint256 cur = toUint(v.value);

        if (op == D_SUB) {
            uint256 amount = abi.decode(val, (uint256));
            if (cur < amount) return; // 乐观值不足，直接跳过（guard 已记录失败分支）

            if (ctx.txId != bytes32(0)) {
                // Freeze 语义：通知本地冻结表预占 amount
                // input: abi.encode(address, uint32, bytes32, bytes32 txId, uint256 amount) = 160 bytes
                bytes memory input = abi.encode(
                    v.contractAddr,
                    v.shardId,
                    v.key,
                    ctx.txId,
                    amount
                );
                (bool ok, bytes memory ret) = PRECOMPILE_CACHE_WRITE.call(input);
                require(ok && ret.length >= 32 && uint8(ret[31]) == 0x01,
                    "JOYUE: freeze failed (insufficient available balance)");
            }
            // 更新乐观值（本地视图）
            v.value = abi.encode(cur - amount);
            return;
        }

        // D_ADD / D_SET / D_BIT_* ：快进写缓存（不修改版本号）
        // 代理合约的缓存修改仅更新乐观值，版本号由主合约 commit 时更新
        uint256 newVal = cur;
        if (op == D_ADD) {
            newVal = cur + abi.decode(val, (uint256));
        } else if (op == D_SET) {
            newVal = abi.decode(val, (uint256));
        } else if (op == D_BIT_OR) {
            newVal = cur | abi.decode(val, (uint256));
        } else if (op == D_BIT_CLEAR) {
            newVal = cur & ~abi.decode(val, (uint256));
        } else if (op == D_BIT_XOR) {
            newVal = cur ^ abi.decode(val, (uint256));
        } else {
            return;
        }

        // 保持版本不变：代理合约不能修改权威状态版本，仅更新本地乐观值
        uint64 versionUnchanged = v.version;
        // Write 语义：abi.encode(address, uint32, bytes32, uint256 value, uint64 version) = 160 bytes
        bytes memory input = abi.encode(
            v.contractAddr,
            v.shardId,
            v.key,
            newVal,
            versionUnchanged
        );
        (bool success, ) = PRECOMPILE_CACHE_WRITE.call(input);
        if (success) {
            v.value = abi.encode(newVal);
            // v.version 保持不变，不递增
        }
    }
}


